# Generated by Django 5.2.3 on 2025-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
